version: '3.8'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
      - '5000:5000'
    volumes:
      - /opt/nexus_nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/nexus_nginx/certs:/etc/letsencrypt
        # links:
        # - nexus
        # command: [ nginx, '-g', 'daemon off;' ]

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /opt/nexus_nginx/certs:/etc/letsencrypt
    entrypoint: sh -c "trap 'exit 0' INT; while :; do sleep 86400 & wait $${!}; certbot renew; done"
    command: certonly --manual --preferred-challenges dns --keep-until-expiring -d YourDomainName

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      #- "8081:8081"
      #- "5001:5001"
    volumes:
      - /opt/nexus_nginx/data/nexus/nexus-data:/nexus-data
    restart: unless-stopped
